version: '3.8'
services:
  bgprivatetour:
    container_name: bgprivatetour
    restart: unless-stopped
    working_dir: /usr/src/app
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.next:/usr/src/app/.next
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./.eslintrc.json:/usr/src/app/.eslintrc.json
      - ./next-env.d.ts:/usr/src/app/next-env.d.ts
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./postcss.config.js:/usr/src/app/postcss.config.js
      - ./tailwind.config.js:/usr/src/app/tailwind.config.js
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - node_data:/usr/src/app/node_modules
    networks:
      - docker-net

volumes:
  node_data:

networks:
  docker-net:
    external: true