version: "3.7"

services:
  bgprivate-react:
    container_name: bgPrivate-react
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - docker-net

networks:
  docker-net:
    external: true